### ISSUE TITLE
Make available for Ubuntu 20.04

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-abinit#2]
Currently, `libblacs-mpi-dev` is not available by default via `apt install`.
Perhaps it is available vi another repository?

```yaml
- name: Add some repository
  become: true
  become_user: "{{ root_user }}"
  apt_repository:
    repo: ppa:some-repo
    state: present
```
